### PR TITLE
feat: Ongeki support

### PR DESCRIPTION
**Pull request by nyairobi**
Please make a new tag of [rg-stats](https://github.com/TNG-dev/rg-stats) because the latest one is still without Ongeki support.

### CODE REVIEW

**Comment by zkldi** [comment]
Heya, this is on the backburner for reviews for the time being. I might get around to this this weekend. Sorry.

**Comment by zkldi** [comment]
MUSTFIX:

- Chart notecount should not be nullable and data must be correct for all charts
- OR: Do away with all notecount information and just store platscore, we'll get around to it later (as we do in our SDVX exscore impl)

- Do away with `lessNaiveScore` and `isHot` and all that stuff.

Other than that this all looks OK!

**Comment by nyairobi** [comment]
> * OR: Do away with all notecount information and just store platscore, we'll get around to it later (as we do in our SDVX exscore impl)

Done that after figuring it would be difficult to obtain "correct" data for all charts.

**Comment by zkldi** [comment]
this looks good, i'll merge this up tonight.

**Pull request merged**
