### PR TITLE
Moved IsValidURL for Callback URLS to array based

### PR DESCRIPTION
**Pull request by Fluzzarn**
List taken from Twitter (lol)'s disallowed callback protocol list.

### CODE REVIEW

**Comment by zkldi** [comment]
what's this for? this array based solution requires active maintenance against future potentially insecure standards.

is there something wrong with just supporting HTTP and HTTPS? that's how we send the msgs anyway.

**Comment by Fluzzarn** [comment]
The reason for this is because mobile apps don't use http/https for callback urls in an oauth2 flow. Both platforms have the app register a uri scheme that the OS knows to redirect to the app.

**Comment by zkldi** [comment]
Interesting. Is there no way to make this an agreed upon constant so it can be whitelisted? otherwise, this blacklist would require constant maintenance and potentially be a security hole.

**Comment by Fluzzarn** [comment]
Reading up on what [oauth recommends](https://www.oauth.com/oauth2-servers/redirect-uris/redirect-uris-native-apps/) oauth recommends in this scenario and places usually go two routes:
1) Incorporate the app id into the url scheme
2) Have the url scheme follow a pattern that is validated on the server side e.g. tachiApp(whatever)://

The second one can work since it's still a whitelist for "http/https/whateverpattern" and doesn't require any UI changes

**Comment by zkldi** [comment]
i like the pattern. is prefixing with `tachi-` ok?

**Comment by zkldi** [comment]
not off my radar, just will be done later. probably thursday. remind me on discord if i haven't.

**Pull request merged**
