### PR TITLE
Add `inGameID` matching support for maimai DX and support nullable `inGameID`s in general

### PR DESCRIPTION
**Pull request by beerpiss**
While `inGameID` being nullable isn't ideal, I am unfortunately not capable of acquiring recent enough data to fill in all of them. 

This should be the last roadblock against network support (MYT) for maimai DX.

While we're here, also fix up chart data for a few BUDDiES+ songs that were wrongfully marked as being available in older versions.

### CODE REVIEW

**Comment by beerpiss** [comment]
Unrelated to the PR at hand but while fixing custom tests for seeds it turns out Rising in the Sun SPH has a different level than levelNum. Is this intended?
```
[CUSTOM VALIDATING] charts-iidx
[ERR] charts-iidx.json | Level and LevelNum should align | kors k feat.Rie - Rising in the Sun(original mix) (761) - SP HYPER (84375665ccc91a7f6e418322d914defe3083fdf7)
[FAILED] charts-iidx. GOOD: 53921, BAD: 1(100.00%).
```

**Comment by zkldi** [comment]
> Unrelated to the PR at hand but while fixing custom tests for seeds it turns out Rising in the Sun SPH has a different level than levelNum. Is this intended?
> 
> ```
> [CUSTOM VALIDATING] charts-iidx
> [ERR] charts-iidx.json | Level and LevelNum should align | kors k feat.Rie - Rising in the Sun(original mix) (761) - SP HYPER (84375665ccc91a7f6e418322d914defe3083fdf7)
> [FAILED] charts-iidx. GOOD: 53921, BAD: 1(100.00%).
> ```

nope. how did this happen?

**Comment by beerpiss** [comment]
> nope. how did this happen?

Looks like it's been there [since the very beginning](https://raw.githubusercontent.com/zkldi/Tachi/969ddc3014bf16a284543a44e352affef2022479/database-seeds/collections/charts-iidx.json).

**Comment by zkldi** [comment]
Odd, I wonder why the tests only just now started failing :thinking: 

Could you fix it? And then I'll check the rest of this PR out.

**Comment by beerpiss** [comment]
> Odd, I wonder why the tests only just now started failing 🤔
> 
> Could you fix it? And then I'll check the rest of this PR out.

The custom tests written only had test functions return true or false:

https://github.com/zkldi/Tachi/blob/main/database-seeds/scripts/test/custom.test.ts#L8-L12

but the calling site expected it to throw:

https://github.com/zkldi/Tachi/blob/main/database-seeds/scripts/test/custom.test.ts#L92-L104

which it never did, so all custom tests apparently "passed".

Before the custom seeds validation, I don't think there were any tests that forced `level` and `levelNum` to agree on each other. Anyways, that should be fixed.

**Comment by zkldi** [comment]
> > Odd, I wonder why the tests only just now started failing 🤔
> > Could you fix it? And then I'll check the rest of this PR out.
> 
> The custom tests written only had test functions return true or false:
> 
> [`main`/database-seeds/scripts/test/custom.test.ts#L8-L12](https://github.com/zkldi/Tachi/blob/main/database-seeds/scripts/test/custom.test.ts?rgh-link-date=2024-06-18T15%3A18%3A47Z#L8-L12)
> 
> but the calling site expected it to throw:
> 
> [`main`/database-seeds/scripts/test/custom.test.ts#L92-L104](https://github.com/zkldi/Tachi/blob/main/database-seeds/scripts/test/custom.test.ts?rgh-link-date=2024-06-18T15%3A18%3A47Z#L92-L104)
> 
> which it never did, so all custom tests apparently "passed".
> 
> Before the custom seeds validation, I don't think there were any tests that forced `level` and `levelNum` to agree with each other. Anyways, that should be fixed.

god i'm such a terrible programmer LOL

**Comment by beerpiss** [comment]
well the "restore branch" button is convenient

**Comment by zkldi** [comment]
Looks excellent. Thank you so much for sorting this out and sorry for such a long delay on getting around to it.

**Pull request merged**
