### PR TITLE
feat: add myt ongeki support

### PR DESCRIPTION
**Pull request by albshin**
Adds API import support on MYT for Ongeki

Some changes are due to Prettier formatting the file.

### CODE REVIEW

**Comment by zkldi** [comment]
Have you tested this code against real myt-ongeki? The code didn't compile.

**Comment by zkldi** [comment]
+bot diff

**Comment by albshin** [comment]
> Have you tested this code against real myt-ongeki? The code didn't compile.

Yes I have. Worked fine on my end when I ran it on a local server.

**Comment by zkldi** [comment]
Merged then, let me know if there are any issues in prod.

**Pull request merged**
